# This is a basic workflow to help you get started with Actions

name: Authenticode Sign

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Authenticode-Sign:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download the Windows Raw un-packaged exe Artifact
        uses: actions/download-artifact@v2
        with:
          # Artifact name
          name: WindowsRawExe
          # Destination path
          path: Downloads

      # Runs a single command using the runners shell
      - name: Set up .Net CLI
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      # Install the Azure Sign Tool for authenticode signing
      - name: Install Azure Sign Tool
      - run: dotnet tool install AzureSignTool
